version: '3.6'
services:
  tlsrouter:
    build: "./docker/tlsrouter"
    environment:
      - ZDXSV_DNAS_IP=192.168.0.3
      - ZDXSV_LOGIN_PUBLIC_IP=192.168.0.3
    ports:
      - "443:443"
      - "53:53/udp"
  dnas:
    build: "./docker/dnas"