version: 2

executors:
  default:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.2
    working_directory: /go/src/github.com/inada-s/zdxsv
    environment:
      - GO111MODULE: "on"

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - run: go mod download
      - run: make ci