version: 2.1

executors:
  default:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.12.2
    working_directory: /go/src/github.com/inada-s/zdxsv
    environment:
      - GO111MODULE: "on"

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run: go mod download
      - persist_to_workspace:
        root: /go
        paths:
          - src
          - bin
          - pkg/mod/cache

  build:
    executor:
      name: default
    steps:
      - attach_workspace:
        at: /go
      - run: make ci

workflows:
  build-and-test:
    jobs:
      - setup
      - build:
          requires:
            - setup

