// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v7.35.1
// source: pkg/proto/zdxsv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type and Packet field numbers 20-25 are gdxsv's (inada-s/gdxsv gdxsv/proto/gdxsv.proto);
// 22/23 (round event / result) are unused: a zdxsv replay has no round data.
type MessageType int32

const (
	MessageType_HelloServer                     MessageType = 1
	MessageType_Ping                            MessageType = 2
	MessageType_Pong                            MessageType = 3
	MessageType_Battle                          MessageType = 4
	MessageType_SpectatorInputPushType          MessageType = 20
	MessageType_SpectatorInputAckType           MessageType = 21
	MessageType_SpectatorSubscribeType          MessageType = 24
	MessageType_SpectatorSubscribeChallengeType MessageType = 25
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		1:  "HelloServer",
		2:  "Ping",
		3:  "Pong",
		4:  "Battle",
		20: "SpectatorInputPushType",
		21: "SpectatorInputAckType",
		24: "SpectatorSubscribeType",
		25: "SpectatorSubscribeChallengeType",
	}
	MessageType_value = map[string]int32{
		"HelloServer":                     1,
		"Ping":                            2,
		"Pong":                            3,
		"Battle":                          4,
		"SpectatorInputPushType":          20,
		"SpectatorInputAckType":           21,
		"SpectatorSubscribeType":          24,
		"SpectatorSubscribeChallengeType": 25,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_zdxsv_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_pkg_proto_zdxsv_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MessageType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MessageType(num)
	return nil
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{0}
}

type BattleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *string `protobuf:"bytes,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	Seq    *uint32 `protobuf:"varint,2,req,name=seq" json:"seq,omitempty"`
	Body   []byte  `protobuf:"bytes,3,req,name=body" json:"body,omitempty"`
}

func (x *BattleMessage) Reset() {
	*x = BattleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleMessage) ProtoMessage() {}

func (x *BattleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleMessage.ProtoReflect.Descriptor instead.
func (*BattleMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{0}
}

func (x *BattleMessage) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *BattleMessage) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *BattleMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type PingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp *int64  `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	UserId    *string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{1}
}

func (x *PingMessage) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *PingMessage) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type PongMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp  *int64  `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	UserId     *string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	PublicAddr *string `protobuf:"bytes,3,opt,name=public_addr,json=publicAddr" json:"public_addr,omitempty"`
}

func (x *PongMessage) Reset() {
	*x = PongMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PongMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMessage) ProtoMessage() {}

func (x *PongMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMessage.ProtoReflect.Descriptor instead.
func (*PongMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{2}
}

func (x *PongMessage) GetTimestamp() int64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *PongMessage) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *PongMessage) GetPublicAddr() string {
	if x != nil && x.PublicAddr != nil {
		return *x.PublicAddr
	}
	return ""
}

type HelloServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId *string `protobuf:"bytes,1,req,name=session_id,json=sessionId" json:"session_id,omitempty"`
	Ok        *bool   `protobuf:"varint,2,opt,name=ok" json:"ok,omitempty"`
}

func (x *HelloServerMessage) Reset() {
	*x = HelloServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloServerMessage) ProtoMessage() {}

func (x *HelloServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloServerMessage.ProtoReflect.Descriptor instead.
func (*HelloServerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{3}
}

func (x *HelloServerMessage) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *HelloServerMessage) GetOk() bool {
	if x != nil && x.Ok != nil {
		return *x.Ok
	}
	return false
}

// Live spectating (pkg/lobby/spectator.go): the battle's uplink participant pushes
// to the lobby's UDP socket, the lobby pushes to each subscribed spectator. Each
// stream (header, start state, inputs) resends from the receiver's ack.
// Fields 1-10 as gdxsv; zdxsv's from 40.
type SpectatorInputPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleCode  *string `protobuf:"bytes,1,opt,name=battle_code,json=battleCode" json:"battle_code,omitempty"`
	SessionId   *int32  `protobuf:"varint,2,opt,name=session_id,json=sessionId" json:"session_id,omitempty"`      // uplink -> lobby: the battle's ggpo_session
	StartFrame  *int32  `protobuf:"varint,3,opt,name=start_frame,json=startFrame" json:"start_frame,omitempty"`   // first frame of input_data
	CloseReason *string `protobuf:"bytes,8,opt,name=close_reason,json=closeReason" json:"close_reason,omitempty"` // set: the battle ended at start_frame
	Header      []byte  `protobuf:"bytes,10,opt,name=header" json:"header,omitempty"`                             // a replay BattleLogFile (pcsx2 Zdxsv/replay.proto) without inputs and start_state
	InputData   []byte  `protobuf:"bytes,40,opt,name=input_data,json=inputData" json:"input_data,omitempty"`      // frames x frame_bytes
	FrameBytes  *int32  `protobuf:"varint,41,opt,name=frame_bytes,json=frameBytes" json:"frame_bytes,omitempty"`  // players x input_size
	State       []byte  `protobuf:"bytes,42,opt,name=state" json:"state,omitempty"`                               // a chunk of the start state (BattleLogFile.start_state)
	StateOffset *int32  `protobuf:"varint,43,opt,name=state_offset,json=stateOffset" json:"state_offset,omitempty"`
	StateTotal  *int32  `protobuf:"varint,44,opt,name=state_total,json=stateTotal" json:"state_total,omitempty"`
}

func (x *SpectatorInputPush) Reset() {
	*x = SpectatorInputPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpectatorInputPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectatorInputPush) ProtoMessage() {}

func (x *SpectatorInputPush) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectatorInputPush.ProtoReflect.Descriptor instead.
func (*SpectatorInputPush) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{4}
}

func (x *SpectatorInputPush) GetBattleCode() string {
	if x != nil && x.BattleCode != nil {
		return *x.BattleCode
	}
	return ""
}

func (x *SpectatorInputPush) GetSessionId() int32 {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return 0
}

func (x *SpectatorInputPush) GetStartFrame() int32 {
	if x != nil && x.StartFrame != nil {
		return *x.StartFrame
	}
	return 0
}

func (x *SpectatorInputPush) GetCloseReason() string {
	if x != nil && x.CloseReason != nil {
		return *x.CloseReason
	}
	return ""
}

func (x *SpectatorInputPush) GetHeader() []byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SpectatorInputPush) GetInputData() []byte {
	if x != nil {
		return x.InputData
	}
	return nil
}

func (x *SpectatorInputPush) GetFrameBytes() int32 {
	if x != nil && x.FrameBytes != nil {
		return *x.FrameBytes
	}
	return 0
}

func (x *SpectatorInputPush) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SpectatorInputPush) GetStateOffset() int32 {
	if x != nil && x.StateOffset != nil {
		return *x.StateOffset
	}
	return 0
}

func (x *SpectatorInputPush) GetStateTotal() int32 {
	if x != nil && x.StateTotal != nil {
		return *x.StateTotal
	}
	return 0
}

// Receiver -> sender: how much of each stream arrived contiguously.
type SpectatorInputAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleCode *string `protobuf:"bytes,1,opt,name=battle_code,json=battleCode" json:"battle_code,omitempty"`
	AckFrame   *int32  `protobuf:"varint,2,opt,name=ack_frame,json=ackFrame" json:"ack_frame,omitempty"`
	HeaderAck  *bool   `protobuf:"varint,40,opt,name=header_ack,json=headerAck" json:"header_ack,omitempty"`
	StateAck   *int32  `protobuf:"varint,41,opt,name=state_ack,json=stateAck" json:"state_ack,omitempty"` // bytes
	CloseAck   *bool   `protobuf:"varint,42,opt,name=close_ack,json=closeAck" json:"close_ack,omitempty"`
}

func (x *SpectatorInputAck) Reset() {
	*x = SpectatorInputAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpectatorInputAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectatorInputAck) ProtoMessage() {}

func (x *SpectatorInputAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectatorInputAck.ProtoReflect.Descriptor instead.
func (*SpectatorInputAck) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{5}
}

func (x *SpectatorInputAck) GetBattleCode() string {
	if x != nil && x.BattleCode != nil {
		return *x.BattleCode
	}
	return ""
}

func (x *SpectatorInputAck) GetAckFrame() int32 {
	if x != nil && x.AckFrame != nil {
		return *x.AckFrame
	}
	return 0
}

func (x *SpectatorInputAck) GetHeaderAck() bool {
	if x != nil && x.HeaderAck != nil {
		return *x.HeaderAck
	}
	return false
}

func (x *SpectatorInputAck) GetStateAck() int32 {
	if x != nil && x.StateAck != nil {
		return *x.StateAck
	}
	return 0
}

func (x *SpectatorInputAck) GetCloseAck() bool {
	if x != nil && x.CloseAck != nil {
		return *x.CloseAck
	}
	return false
}

// Spectator -> lobby, resent every 2 s as keepalive. An empty battle_code asks for
// the newest live battle: the challenge names it.
type SpectatorSubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleCode *string `protobuf:"bytes,1,opt,name=battle_code,json=battleCode" json:"battle_code,omitempty"`
	FromFrame  *int32  `protobuf:"varint,3,opt,name=from_frame,json=fromFrame" json:"from_frame,omitempty"`
	Cookie     []byte  `protobuf:"bytes,4,opt,name=cookie" json:"cookie,omitempty"` // the challenge's 16 bytes; 16 zero bytes at first
}

func (x *SpectatorSubscribeRequest) Reset() {
	*x = SpectatorSubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpectatorSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectatorSubscribeRequest) ProtoMessage() {}

func (x *SpectatorSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectatorSubscribeRequest.ProtoReflect.Descriptor instead.
func (*SpectatorSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{6}
}

func (x *SpectatorSubscribeRequest) GetBattleCode() string {
	if x != nil && x.BattleCode != nil {
		return *x.BattleCode
	}
	return ""
}

func (x *SpectatorSubscribeRequest) GetFromFrame() int32 {
	if x != nil && x.FromFrame != nil {
		return *x.FromFrame
	}
	return 0
}

func (x *SpectatorSubscribeRequest) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

type SpectatorSubscribeChallenge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BattleCode *string `protobuf:"bytes,1,opt,name=battle_code,json=battleCode" json:"battle_code,omitempty"`
	Cookie     []byte  `protobuf:"bytes,2,opt,name=cookie" json:"cookie,omitempty"`
}

func (x *SpectatorSubscribeChallenge) Reset() {
	*x = SpectatorSubscribeChallenge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpectatorSubscribeChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectatorSubscribeChallenge) ProtoMessage() {}

func (x *SpectatorSubscribeChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectatorSubscribeChallenge.ProtoReflect.Descriptor instead.
func (*SpectatorSubscribeChallenge) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{7}
}

func (x *SpectatorSubscribeChallenge) GetBattleCode() string {
	if x != nil && x.BattleCode != nil {
		return *x.BattleCode
	}
	return ""
}

func (x *SpectatorSubscribeChallenge) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

type Packet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type                            *MessageType                 `protobuf:"varint,1,req,name=type,enum=proto.MessageType" json:"type,omitempty"`
	Seq                             *uint32                      `protobuf:"varint,2,opt,name=seq" json:"seq,omitempty"`
	Ack                             *uint32                      `protobuf:"varint,3,opt,name=ack" json:"ack,omitempty"`
	HelloServerData                 *HelloServerMessage          `protobuf:"bytes,10,opt,name=hello_server_data,json=helloServerData" json:"hello_server_data,omitempty"`
	PingData                        *PingMessage                 `protobuf:"bytes,11,opt,name=ping_data,json=pingData" json:"ping_data,omitempty"`
	PongData                        *PongMessage                 `protobuf:"bytes,12,opt,name=pong_data,json=pongData" json:"pong_data,omitempty"`
	BattleData                      []*BattleMessage             `protobuf:"bytes,13,rep,name=battle_data,json=battleData" json:"battle_data,omitempty"`
	SpectatorInputPushData          *SpectatorInputPush          `protobuf:"bytes,20,opt,name=spectator_input_push_data,json=spectatorInputPushData" json:"spectator_input_push_data,omitempty"`
	SpectatorInputAckData           *SpectatorInputAck           `protobuf:"bytes,21,opt,name=spectator_input_ack_data,json=spectatorInputAckData" json:"spectator_input_ack_data,omitempty"`
	SpectatorSubscribeData          *SpectatorSubscribeRequest   `protobuf:"bytes,24,opt,name=spectator_subscribe_data,json=spectatorSubscribeData" json:"spectator_subscribe_data,omitempty"`
	SpectatorSubscribeChallengeData *SpectatorSubscribeChallenge `protobuf:"bytes,25,opt,name=spectator_subscribe_challenge_data,json=spectatorSubscribeChallengeData" json:"spectator_subscribe_challenge_data,omitempty"`
}

func (x *Packet) Reset() {
	*x = Packet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_zdxsv_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_zdxsv_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_pkg_proto_zdxsv_proto_rawDescGZIP(), []int{8}
}

func (x *Packet) GetType() MessageType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MessageType_HelloServer
}

func (x *Packet) GetSeq() uint32 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *Packet) GetAck() uint32 {
	if x != nil && x.Ack != nil {
		return *x.Ack
	}
	return 0
}

func (x *Packet) GetHelloServerData() *HelloServerMessage {
	if x != nil {
		return x.HelloServerData
	}
	return nil
}

func (x *Packet) GetPingData() *PingMessage {
	if x != nil {
		return x.PingData
	}
	return nil
}

func (x *Packet) GetPongData() *PongMessage {
	if x != nil {
		return x.PongData
	}
	return nil
}

func (x *Packet) GetBattleData() []*BattleMessage {
	if x != nil {
		return x.BattleData
	}
	return nil
}

func (x *Packet) GetSpectatorInputPushData() *SpectatorInputPush {
	if x != nil {
		return x.SpectatorInputPushData
	}
	return nil
}

func (x *Packet) GetSpectatorInputAckData() *SpectatorInputAck {
	if x != nil {
		return x.SpectatorInputAckData
	}
	return nil
}

func (x *Packet) GetSpectatorSubscribeData() *SpectatorSubscribeRequest {
	if x != nil {
		return x.SpectatorSubscribeData
	}
	return nil
}

func (x *Packet) GetSpectatorSubscribeChallengeData() *SpectatorSubscribeChallenge {
	if x != nil {
		return x.SpectatorSubscribeChallengeData
	}
	return nil
}

var File_pkg_proto_zdxsv_proto protoreflect.FileDescriptor

var file_pkg_proto_zdxsv_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x7a, 0x64, 0x78, 0x73,
	0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e,
	0x0a, 0x0d, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18,
	0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x44,
	0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x02, 0x28, 0x03,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x65, 0x0a, 0x0b, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x41, 0x64, 0x64, 0x72, 0x22, 0x43, 0x0a, 0x12, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x22, 0xca, 0x02, 0x0a, 0x12, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x28, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x29, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x2a, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x2b, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0b, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x2c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xaa, 0x01,
	0x0a, 0x11, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x41, 0x63, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x6b, 0x5f, 0x66, 0x72, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x63, 0x6b, 0x46, 0x72, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x6b, 0x18,
	0x28, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x41, 0x63, 0x6b,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x29, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x2a, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x41, 0x63, 0x6b, 0x22, 0x73, 0x0a, 0x19, 0x53, 0x70,
	0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x72, 0x6f, 0x6d,
	0x5f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x66, 0x72,
	0x6f, 0x6d, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x22,
	0x56, 0x0a, 0x1b, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x22, 0xaa, 0x05, 0x0a, 0x06, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65,
	0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x45,
	0x0a, 0x11, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x0f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x09, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x70, 0x69,
	0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x09, 0x70, 0x6f, 0x6e, 0x67, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x6f, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x70,
	0x6f, 0x6e, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x74, 0x6c,
	0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x54,
	0x0a, 0x19, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x14, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61,
	0x74, 0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x16, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x75, 0x73, 0x68,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x51, 0x0a, 0x18, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f,
	0x72, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x61, 0x63, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x63, 0x6b,
	0x52, 0x15, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x41, 0x63, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x5a, 0x0a, 0x18, 0x73, 0x70, 0x65, 0x63, 0x74,
	0x61, 0x74, 0x6f, 0x72, 0x5f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x16, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x6f, 0x0a, 0x22, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72,
	0x5f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6c, 0x6c,
	0x65, 0x6e, 0x67, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x19, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f,
	0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65,
	0x6e, 0x67, 0x65, 0x52, 0x1f, 0x73, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x68, 0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x2a, 0xb6, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12,
	0x08, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x50, 0x75, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x10,
	0x14, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x41, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x10, 0x15, 0x12, 0x1a, 0x0a, 0x16,
	0x53, 0x70, 0x65, 0x63, 0x74, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x54, 0x79, 0x70, 0x65, 0x10, 0x18, 0x12, 0x23, 0x0a, 0x1f, 0x53, 0x70, 0x65, 0x63,
	0x74, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x43, 0x68,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x10, 0x19, 0x42, 0x11, 0x5a,
	0x0f, 0x7a, 0x64, 0x78, 0x73, 0x76, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_pkg_proto_zdxsv_proto_rawDescOnce sync.Once
	file_pkg_proto_zdxsv_proto_rawDescData = file_pkg_proto_zdxsv_proto_rawDesc
)

func file_pkg_proto_zdxsv_proto_rawDescGZIP() []byte {
	file_pkg_proto_zdxsv_proto_rawDescOnce.Do(func() {
		file_pkg_proto_zdxsv_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_zdxsv_proto_rawDescData)
	})
	return file_pkg_proto_zdxsv_proto_rawDescData
}

var file_pkg_proto_zdxsv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_zdxsv_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_zdxsv_proto_goTypes = []interface{}{
	(MessageType)(0),                    // 0: proto.MessageType
	(*BattleMessage)(nil),               // 1: proto.BattleMessage
	(*PingMessage)(nil),                 // 2: proto.PingMessage
	(*PongMessage)(nil),                 // 3: proto.PongMessage
	(*HelloServerMessage)(nil),          // 4: proto.HelloServerMessage
	(*SpectatorInputPush)(nil),          // 5: proto.SpectatorInputPush
	(*SpectatorInputAck)(nil),           // 6: proto.SpectatorInputAck
	(*SpectatorSubscribeRequest)(nil),   // 7: proto.SpectatorSubscribeRequest
	(*SpectatorSubscribeChallenge)(nil), // 8: proto.SpectatorSubscribeChallenge
	(*Packet)(nil),                      // 9: proto.Packet
}
var file_pkg_proto_zdxsv_proto_depIdxs = []int32{
	0, // 0: proto.Packet.type:type_name -> proto.MessageType
	4, // 1: proto.Packet.hello_server_data:type_name -> proto.HelloServerMessage
	2, // 2: proto.Packet.ping_data:type_name -> proto.PingMessage
	3, // 3: proto.Packet.pong_data:type_name -> proto.PongMessage
	1, // 4: proto.Packet.battle_data:type_name -> proto.BattleMessage
	5, // 5: proto.Packet.spectator_input_push_data:type_name -> proto.SpectatorInputPush
	6, // 6: proto.Packet.spectator_input_ack_data:type_name -> proto.SpectatorInputAck
	7, // 7: proto.Packet.spectator_subscribe_data:type_name -> proto.SpectatorSubscribeRequest
	8, // 8: proto.Packet.spectator_subscribe_challenge_data:type_name -> proto.SpectatorSubscribeChallenge
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_proto_zdxsv_proto_init() }
func file_pkg_proto_zdxsv_proto_init() {
	if File_pkg_proto_zdxsv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_zdxsv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_zdxsv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_zdxsv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PongMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_zdxsv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_zdxsv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpectatorInputPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_zdxsv_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpectatorInputAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_zdxsv_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpectatorSubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_zdxsv_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpectatorSubscribeChallenge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_zdxsv_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Packet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_zdxsv_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_zdxsv_proto_goTypes,
		DependencyIndexes: file_pkg_proto_zdxsv_proto_depIdxs,
		EnumInfos:         file_pkg_proto_zdxsv_proto_enumTypes,
		MessageInfos:      file_pkg_proto_zdxsv_proto_msgTypes,
	}.Build()
	File_pkg_proto_zdxsv_proto = out.File
	file_pkg_proto_zdxsv_proto_rawDesc = nil
	file_pkg_proto_zdxsv_proto_goTypes = nil
	file_pkg_proto_zdxsv_proto_depIdxs = nil
}
